trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  pythonVersion: '3.12'

steps:

# Checkout Source Code
- checkout: self
  fetchDepth: 0

# SonarCloud Prepare
- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'SonarCloud-Service'
    organization: 'rahulnavi26'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'rahulnavi26_Fastapi_project'
    cliProjectName: 'Fastapi_project'
    cliSources: '.'

# Use Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
  displayName: 'Use Python $(pythonVersion)'

# Install Dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

# Validate Python Code
- script: |
    python -m py_compile main.py
  displayName: 'Validate Python Code'

# Test FastAPI Startup
- script: |
    timeout 10s uvicorn main:app --host 0.0.0.0 --port 8000 || true
  displayName: 'Test FastAPI Startup'

# SonarCloud Analysis
- task: SonarCloudAnalyze@3
  displayName: 'Run SonarCloud Analysis'

# Publish SonarCloud Quality Gate
- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish SonarCloud Results'

# Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'fastapi-mongodb-app'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'